Prepare for Release
AntonMaslik/recipes-api pull request #14
Opened 2024-11-29 14:36 UTC by AntonMaslik

2024-11-29 15:13 UTC, sefaplus requested changes

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/models/recipes.repository.ts
> +        }
?????
нееет! Нивкоем случае
Вообще нет

Искать при помощи dynamoose

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/models/recipes.repository.ts
> +        }
а если рецептов 3млн?
Что быстрее кончится)
Мои нервы или память?)

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/models/recipes.repository.ts
> +        }
пустой массив!

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.module.ts
> +                getMinioConfig(configService),
same

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +    ) {}
зачем пустые строки

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +        }
рецепты не уникальы по имени
Это странно

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +        }
пустой массив!
Никогда тип данных не должен сильно различаться!

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +        const start: number = (page - 1) * limit;
Будет там page 1 и у тебя все посыпется

Math.max(page - 1, 0) * limit

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +        const urlPath: string = `${this.configService.getOrThrow<string>('MINIO_ENDPOINT')}:${this.configService.getOrThrow<string>('MINIO_PORT')}/${bucketName}/${objectName}`;
чтоза...
Вынести в функцию хелпер
почему опять лишние пустые строки?

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +
что.. зачем?
Почему не сжедаьб ниже

{
...recipe,
image: urlPath
}

?

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +        return urlPath;
При ошибке возвращается ошибка?
InternalServerError

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +            await this.updateRecipe(id, { image: '', ...recipe });
same

...recipe, image: null

убрать delete!
delete в крайних случаях только!!

2024-11-29 15:13 UTC, sefaplus commented on src/modules/recipes/recipes.service.ts
> +        }
same

2024-11-29 15:13 UTC, sefaplus commented on src/modules/roles/decorators/roles-guard.decorator.ts
> +import { RolesGuard as rG } from '@modules/roles/guards/roles.guard';
зачем RolesGuard as Rg?

Переименуй тогда класс который импортируешь
потом еще пытаться угадай какой импорт что..

2024-11-29 15:13 UTC, sefaplus commented on src/modules/steps/steps.module.ts
> +                getMinioConfig(configService),
same

2024-11-29 15:13 UTC, sefaplus commented on src/modules/steps/steps.service.ts
> +        private readonly configService: ConfigService,
same

2024-11-29 15:13 UTC, sefaplus commented on src/modules/steps/steps.service.ts
> +        });
зачем ...spread?

2024-11-29 15:13 UTC, sefaplus commented on src/modules/steps/steps.service.ts
> +        const urlPath: string = `${this.configService.getOrThrow<string>('MINIO_ENDPOINT')}:${this.configService.getOrThrow<string>('MINIO_PORT')}/${bucketName}/${objectName}`;
helper

2024-11-29 15:13 UTC, sefaplus commented on src/modules/tasks/tasks.service.ts
> +    }
в  генератор!

2024-11-29 15:13 UTC, sefaplus commented on src/modules/tokens/models/tokens.repository.ts
>          }
tokens.length

2024-11-29 15:13 UTC, sefaplus commented on src/modules/tokens/models/tokens.repository.ts
> +        if (tokens.length < 0) {
!tokens.length

2024-11-29 15:13 UTC, sefaplus commented on src/modules/users/models/users.repository.ts
> +        if (users.length > 0) {
users.length

2024-12-01 21:42 UTC, AntonMaslik commented on src/modules/auth/auth.service.ts
>          const newUser = await this.usersRepository.create({
Она не синхронная вроде

import * as bcrypt from 'bcrypt';

export async function generateHash(value: string): Promise<string> {
    const saltRounds = 12;
    const salt = await bcrypt.genSalt(saltRounds);

    return bcrypt.hash(value, salt);
}

2024-12-01 22:45 UTC, AntonMaslik commented on src/modules/recipes/recipes.service.ts
> +        }
Ну по задумке: name - уникальное поле, а в title можно указать одинаковые имена рецептов. Но я исправлю, просто объясняю, почему именно такой подход я использовал =)

2024-12-02 11:03 UTC, sefaplus commented on package.json
> +    "package.json": "^2.0.1",
what is this

2024-12-02 11:05 UTC, sefaplus commented on src/config/cookies.options.ts
> +    maxAge: 60 * 60 * 1000, // 20MIN
Я конечно извиняюсь а как это может быть 20 minutes если это 60?

2024-12-02 11:06 UTC, sefaplus commented on src/modules/auth/resolves/auth.resolver.ts
> +        @Cookie('refreshToken') currentRefreshToken,
почему тип any?

2024-12-02 11:14 UTC, sefaplus commented on src/modules/steps/steps.service.ts
> +            .join('/');
а зачем..
ты хранишь полную ссылку?
должны хранить только UUID

Фронт сам подставит бакет (оно будет у него храниться в ENV). Это нужно, чтобы в случае переезда не приходилось обновлять шаги и их URL. Мы сможет перенести изображения, поменять переменную на фронте и все

2024-12-02 11:14 UTC, sefaplus commented on src/modules/tasks/tasks.service.ts
> +        if (ratedItems.length === 0 || recipes.length === 0) {
!*.length

2024-12-02 11:17 UTC, sefaplus commented on src/modules/tasks/tasks.service.ts
> +        for await (const recipe of this.getRecipeWithAverageRating(
Какой смысл в генераторе которые не делает ничего?

Генератор нужен был для получения оценок рецепта, а не подсчета.
Мы бы получали по 100 оценок для рецепта, делали среднюю, отбрасывали старые 100 и тянули новые сто и по кругу. Смысл в том чтобы память экономить.

А ты получается подтянул 1млн рецептом и 10млн оценок. И сделал генератор чтобы уже по тем что в пмяти итерировать?)

2024-12-02 11:18 UTC, sefaplus commented on src/modules/tasks/tasks.service.ts
> +        const ratedItems: RateModel[] = await this.rateModel.scan().exec();
1 млн рецептов и 10млн оценок :)

Вынести в асинхронный генератор (см другой коммент этого файла)

2024-12-02 11:26 UTC, sefaplus commented on src/modules/tasks/tasks.service.ts
> +        for await (const recipe of this.getRecipeWithAverageRating(
должно быть 2 генератор.
1 для получения рецептов, скажем по 10
И другой для получения оцена для каждорого рецепта, скажем по 100.

и тебя циклы:

```ts
for await(const recipes of getRecipesGenerator({ amount: 10 })) {
    for(const recipe of recipes) {
        const average = await averageRating(recipe.id) // Это функция что внутри себя имеет генератор для подтягивания 100 рецептов за раз и подсчета средней. Что то в духе Reduce.
        // update recipe.rating here 
    }
}

// пример  averageRating
function averateRating(recipeId: string) {
let sum = 0;
let amount = 0 
for await (const ratings of getRatingGenerator({ amount: 100, recipeId })
    sum = sum + raings.reduce((acc, { rate }) => rate + acc , 0);
    length += rating.length
}

return sum / amount;
```

2024-12-02 11:30 UTC, sefaplus commented on src/modules/users/models/users.repository.ts
> +        return null;
return users[0] ?? null

2024-12-03 11:07 UTC, sefaplus approved these changes

2024-12-03 11:09 UTC, merged